apiVersion: apps/v1
kind: Deployment
metadata:
  name: f-f-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: f-f-backend
  template:
    metadata:
      labels:
        app: f-f-backend
    spec:
      containers:
        - name: f-f-backend
          image: refactoring-registry.kr.ncr.ntruss.com/filterfacts-backend:__TAG__

          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: f-f-secret

      imagePullSecrets:
        - name: ncr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  selector:
    app: f-f-backend
  ports:
    - port: 80
      targetPort: 8080
